# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-04 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('dni', models.CharField(max_length=12, unique=True)),
                ('birth_date', models.DateField()),
                ('cover_dni', models.ImageField(upload_to='covers_dni')),
                ('back_cover_dni', models.ImageField(upload_to='back_cover_dni')),
                ('photo', models.ImageField(upload_to='covers')),
            ],
            options={
                'verbose_name': 'Human',
                'verbose_name_plural': 'Humans',
            },
        ),
    ]
